<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Create the legacy base tables that the application depends on but that were
 * never captured as migrations. The original project was generated by InfyOm
 * directly against an existing database, so these tables only ever existed as
 * resources/model_schemas/*.json definitions (+ the models' own metadata) and
 * were absent from any fresh database built purely from migrations.
 *
 * Column definitions are reconstructed from those model_schemas; a few columns
 * that were later added to the live tables out-of-band (e.g. drivers.session)
 * are folded back in. Every create is guarded with Schema::hasTable() so this is
 * a no-op on databases where the legacy tables already exist.
 *
 * Generated by gen_legacy_migration.php.
 */
class CreateLegacyBaseTables extends Migration
{
    public function up()
    {
        if (!Schema::hasTable('advances')) {
            Schema::create('advances', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->dateTime('date');
                $table->string('no', 255);
                $table->bigInteger('driver_id', false, false);
                $table->bigInteger('lorry_id', false, false);
                $table->mediumText('description');
                $table->float('amount', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('bonus')) {
            Schema::create('bonus', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->string('name', 255);
                $table->bigInteger('vendor_id', false, false);
                $table->bigInteger('source_id', false, false);
                $table->bigInteger('destinate_id', false, false);
                $table->float('weight', 10, 2);
                $table->dateTime('bonusstart');
                $table->dateTime('bonusend');
                $table->float('amount', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('claims')) {
            Schema::create('claims', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->dateTime('date');
                $table->string('no', 255);
                $table->bigInteger('driver_id', false, false);
                $table->bigInteger('lorry_id', false, false);
                $table->mediumText('description');
                $table->float('amount', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('commissionbyvendors')) {
            Schema::create('commissionbyvendors', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('lorry_id', false, false);
                $table->bigInteger('vendor_id', false, false);
                $table->integer('commissionlimit', false, false);
                $table->integer('commissionpercentage', false, false);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('compounds')) {
            Schema::create('compounds', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->dateTime('date');
                $table->string('no', 255);
                $table->bigInteger('driver_id', false, false);
                $table->bigInteger('lorry_id', false, false);
                $table->mediumText('description');
                $table->float('amount', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('drivers')) {
            Schema::create('drivers', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->string('name', 255);
                $table->dateTime('birthdate');
                $table->string('email', 255);
                $table->string('phone', 255)->nullable();
                $table->mediumText('address1')->nullable();
                $table->mediumText('address2')->nullable();
                $table->mediumText('address3')->nullable();
                $table->mediumText('address4')->nullable();
                $table->string('grouping', 255)->nullable();
                $table->string('caption', 255)->nullable();
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->string('session', 255)->nullable();
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('driver_location')) {
            Schema::create('driver_location', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->dateTime('date');
                $table->bigInteger('driver_id', false, false);
                $table->bigInteger('kelindan_id', false, false);
                $table->bigInteger('lorry_id', false, false);
                $table->string('latitude', 255);
                $table->string('longitude', 255);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('items')) {
            Schema::create('items', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->string('code', 255);
                $table->string('name', 255);
                $table->float('billingrate', 10, 2);
                $table->float('commissionrate', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('loans')) {
            Schema::create('loans', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->dateTime('date');
                $table->bigInteger('driver_id', false, false);
                $table->mediumText('description');
                $table->float('amount', 10, 2);
                $table->integer('period', false, false);
                $table->float('rate', 10, 2);
                $table->float('totalamount', 10, 2);
                $table->float('monthlyamount', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('loanpayments')) {
            Schema::create('loanpayments', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('loan_id', false, false);
                $table->dateTime('date');
                $table->mediumText('description');
                $table->float('amount', 10, 2);
                $table->string('source', 255);
                $table->integer('payment', false, false);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('locations')) {
            Schema::create('locations', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->string('code', 255);
                $table->string('name', 255);
                $table->bigInteger('source', false, false);
                $table->bigInteger('distination', false, false);
                $table->string('phone', 255)->nullable();
                $table->mediumText('address1')->nullable();
                $table->mediumText('address2')->nullable();
                $table->mediumText('address3')->nullable();
                $table->mediumText('address4')->nullable();
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('paymentdetails')) {
            Schema::create('paymentdetails', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('driver_id', false, false);
                $table->dateTime('datefrom');
                $table->dateTime('dateto');
                $table->bigInteger('month', false, false);
                $table->float('do_amount', 10, 2);
                $table->text('do_list')->nullable();
                $table->float('claim_amount', 10, 2);
                $table->text('claim_list')->nullable();
                $table->float('comp_amount', 10, 2);
                $table->text('comp_list')->nullable();
                $table->float('adv_amount', 10, 2);
                $table->text('adv_list')->nullable();
                $table->float('loanpay_amount', 10, 2);
                $table->text('loanpay_list')->nullable();
                $table->float('bonus_amount', 10, 2);
                $table->text('bonus_list')->nullable();
                $table->float('deduct_amount', 10, 2);
                $table->float('final_amount', 10, 2);
                $table->bigInteger('status', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('permissions')) {
            Schema::create('permissions', function (Blueprint $table) {
                $table->bigInteger('id', true, true);
                $table->string('name', 255);
                $table->string('guard_name', 255);
                $table->timestamps();
            });
        }

        if (!Schema::hasTable('prices')) {
            Schema::create('prices', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('item_id', false, false);
                $table->bigInteger('vendor_id', false, false);
                $table->bigInteger('source_id', false, false);
                $table->bigInteger('destinate_id', false, false);
                $table->integer('minrange', false, false);
                $table->integer('maxrange', false, false);
                $table->float('billingrate', 10, 2);
                $table->float('commissionrate', 10, 2);
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('reports')) {
            Schema::create('reports', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->string('name', 255);
                $table->text('sqlvalue');
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('reportdetails')) {
            Schema::create('reportdetails', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('report_id', false, false);
                $table->string('name', 255);
                $table->string('type', 255);
                $table->text('data');
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('roles')) {
            Schema::create('roles', function (Blueprint $table) {
                $table->bigInteger('id', true, true);
                $table->string('name', 255);
                $table->string('guard_name', 255);
                $table->timestamps();
            });
        }

        if (!Schema::hasTable('role_has_permissions')) {
            Schema::create('role_has_permissions', function (Blueprint $table) {
                $table->bigInteger('permission_id', false, true);
                $table->bigInteger('role_id', false, true);
                $table->bigInteger('id', true, false);
            });
        }

        if (!Schema::hasTable('saveviews')) {
            Schema::create('saveviews', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('user_id', false, false);
                $table->dateTime('date');
                $table->string('view', 255)->nullable();
                $table->integer('recordrow', false, false);
                $table->text('data')->nullable();
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('servicedetails')) {
            Schema::create('servicedetails', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('lorry_id', false, false);
                $table->string('type', 255);
                $table->dateTime('date');
                $table->dateTime('nextdate');
                $table->float('amount', 10, 2);
                $table->string('remark', 255)->nullable();
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('model_has_roles')) {
            Schema::create('model_has_roles', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->bigInteger('role_id', false, true);
                $table->string('model_type', 255);
                $table->bigInteger('model_id', false, true);
            });
        }

        if (!Schema::hasTable('vendors')) {
            Schema::create('vendors', function (Blueprint $table) {
                $table->bigInteger('id', true, false);
                $table->string('code', 255);
                $table->string('name', 255);
                $table->string('phone', 255)->nullable();
                $table->bigInteger('status', false, false);
                $table->mediumText('STR_UDF1')->nullable();
                $table->mediumText('STR_UDF2')->nullable();
                $table->mediumText('STR_UDF3')->nullable();
                $table->integer('INT_UDF1', false, false);
                $table->integer('INT_UDF2', false, false);
                $table->integer('INT_UDF3', false, false);
                $table->timestamps();
                $table->softDeletes();
            });
        }

        if (!Schema::hasTable('users')) {
            Schema::create('users', function (Blueprint $table) {
                $table->bigInteger('id', true, true);
                $table->string('name', 255);
                $table->string('email', 255);
                $table->dateTime('email_verified_at')->nullable();
                $table->string('password', 255);
                $table->rememberToken();
                $table->timestamps();
            });
        }

        if (!Schema::hasTable('model_has_permissions')) {
            Schema::create('model_has_permissions', function (Blueprint $table) {
                $table->bigInteger('permission_id', false, true);
                $table->string('model_type', 255);
                $table->bigInteger('model_id', false, true);
                $table->index(['model_id', 'model_type']);
            });
        }
    }

    public function down()
    {
        foreach (['model_has_permissions', 'users', 'vendors', 'model_has_roles', 'servicedetails', 'saveviews', 'role_has_permissions', 'roles', 'reportdetails', 'reports', 'prices', 'permissions', 'paymentdetails', 'locations', 'loanpayments', 'loans', 'items', 'driver_location', 'drivers', 'compounds', 'commissionbyvendors', 'claims', 'bonus', 'advances'] as $t) {
            Schema::dropIfExists($t);
        }
    }
}